# Generated by Django 3.2.4 on 2024-07-18 12:25

import badi_ticket.models
import badi_utils.dynamic_models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Message Text')),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/', validators=[badi_ticket.models.MaxFileLengthValidator(1)], verbose_name='File')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is seen by user')),
                ('is_seen_by_admin', models.BooleanField(default=False, verbose_name='Is seen by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (),
            },
            bases=(models.Model, badi_utils.dynamic_models.BadiModel),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('category', models.CharField(choices=[('sell', 'Sell'), ('public_question', 'Public question'), ('technical_question', 'Technical question'), ('authentication', 'Authentication'), ('complaint', 'Complaint'), ('financial', 'Financial'), ('other', 'Other')], default='public_question', max_length=50)),
                ('is_closed', models.BooleanField(default=False, verbose_name='is Closed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Ticket',
                'permissions': (('can_ticket', 'Manage Tickets'),),
            },
            bases=(models.Model, badi_utils.dynamic_models.BadiModel),
        ),
    ]
